------------------------------------------------------ Función para calcular el saldo actual de una cuenta de cobro
CREATE OR REPLACE FUNCTION FU_CALC_V_ACTUAL (
    PK_CONJUNTO IN CONJUNTO.COD_CONJUNTO%TYPE,
    PK_BLOQUE IN APARTAMENTO.COD_BLOQUE%TYPE,
    PK_APTO IN APARTAMENTO.COD_APARTAMENTO%TYPE,
    PN_MES IN CUENTA_COBRO.PERIODO_MES_CUENTA%TYPE,
    PN_ANIO IN CUENTA_COBRO.PERIODO_ANIO_CUENTA%TYPE
) RETURN CUENTA_COBRO.SALDO_ACTUAL%TYPE AS
    LS_ACTUAL CUENTA_COBRO.SALDO_ACTUAL%TYPE;
BEGIN
    SELECT
        SALDO_ACTUAL INTO LS_ACTUAL
    FROM
        CUENTA_COBRO
    WHERE
        PERIODO_MES_CUENTA = PN_MES
        AND PERIODO_ANIO_CUENTA = PN_ANIO
        AND COD_CONJUNTO = PK_CONJUNTO
        AND COD_BLOQUE = PK_BLOQUE
        AND COD_APARTAMENTO = PK_APTO;
    RETURN LS_ACTUAL;
EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20001, 'FU_CALC_V_ACTUAL Ha ocurrido un error: '
            || SQLCODE
            || SQLERRM);
END FU_CALC_V_ACTUAL;
/

------------------------------------------------------ Función para calcular el saldo pendiente de una cuenta de cobro
CREATE OR REPLACE FUNCTION FU_CALC_V_PENDIENTE (
    PK_CONJUNTO IN CONJUNTO.COD_CONJUNTO%TYPE,
    PK_BLOQUE IN APARTAMENTO.COD_BLOQUE%TYPE,
    PK_APTO IN APARTAMENTO.COD_APARTAMENTO%TYPE,
    PN_MES IN CUENTA_COBRO.PERIODO_MES_CUENTA%TYPE,
    PN_ANIO IN CUENTA_COBRO.PERIODO_ANIO_CUENTA%TYPE
) RETURN CUENTA_COBRO.SALDO_PENDIENTE%TYPE AS
    LS_PENDIENTE CUENTA_COBRO.SALDO_PENDIENTE%TYPE;
BEGIN
    SELECT
        SALDO_PENDIENTE INTO LS_PENDIENTE
    FROM
        CUENTA_COBRO
    WHERE
        PERIODO_MES_CUENTA = PN_MES
        AND PERIODO_ANIO_CUENTA = PN_ANIO
        AND COD_CONJUNTO = PK_CONJUNTO
        AND COD_BLOQUE = PK_BLOQUE
        AND COD_APARTAMENTO = PK_APTO;
    RETURN LS_PENDIENTE;
EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20001, 'FU_CALC_V_PENDIENTE Ha ocurrido un error: '
            || SQLCODE
            || SQLERRM);
END FU_CALC_V_PENDIENTE;
/

------------------------------------------------------ Función para saber si existe una cuenta de cobro dada
CREATE OR REPLACE FUNCTION FU_EXISTENCIA_CUENTA (
    PK_CONJUNTO IN CONJUNTO.COD_CONJUNTO%TYPE,
    PK_BLOQUE IN APARTAMENTO.COD_BLOQUE%TYPE,
    PK_APTO IN APARTAMENTO.COD_APARTAMENTO%TYPE,
    PN_MES IN CUENTA_COBRO.PERIODO_MES_CUENTA%TYPE,
    PN_ANIO IN CUENTA_COBRO.PERIODO_ANIO_CUENTA%TYPE
) RETURN BOOLEAN AS
    LK_CUENTA CUENTA_COBRO.COD_CUENTA_COBRO%TYPE;
BEGIN
    SELECT
        COD_CUENTA_COBRO INTO LK_CUENTA
    FROM
        CUENTA_COBRO
    WHERE
        COD_CONJUNTO = PK_CONJUNTO
        AND COD_BLOQUE = PK_BLOQUE
        AND COD_APARTAMENTO = PK_APTO
        AND PERIODO_ANIO_CUENTA = PN_MES
        AND PERIODO_ANIO_CUENTA = PN_ANIO;
    IF LK_CUENTA IS NOT NULL THEN
        RETURN TRUE;
    ELSE
        RETURN FALSE;
    END IF;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN FALSE;
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20001, 'FU_EXISTENCIA_CUENTA Ha ocurrido un error: '
            || SQLCODE
            || SQLERRM);
END FU_EXISTENCIA_CUENTA;
/

------------------------------------------------------ Función para saber si existe una cuenta de cobro dada
CREATE OR REPLACE FUNCTION FU_ES_SALDO_POSITIVO (
    PK_CONJUNTO IN CONJUNTO.COD_CONJUNTO%TYPE,
    PK_BLOQUE IN APARTAMENTO.COD_BLOQUE%TYPE,
    PK_APTO IN APARTAMENTO.COD_APARTAMENTO%TYPE,
    PN_MES IN CUENTA_COBRO.PERIODO_MES_CUENTA%TYPE,
    PN_ANIO IN CUENTA_COBRO.PERIODO_ANIO_CUENTA%TYPE,
    PV_SALDO_ACTUAL IN CUENTA_COBRO.SALDO_ACTUAL%TYPE,
    PV_SALDO_PENDIENTE IN CUENTA_COBRO.SALDO_PENDIENTE%TYPE,
    PV_PAGADO IN PAGO.VALOR_PAGADO%TYPE
) RETURN BOOLEAN AS
    LV_SALDO CUENTA_COBRO.SALDO_ACTUAL%TYPE;
BEGIN
    SELECT
        PV_SALDO_ACTUAL - ( PV_PAGADO + PV_SALDO_PENDIENTE ) INTO LV_SALDO
    FROM
        CUENTA_COBRO
    WHERE
        COD_CONJUNTO = PK_CONJUNTO
        AND COD_BLOQUE = PK_BLOQUE
        AND COD_APARTAMENTO = PK_APTO
        AND PERIODO_MES_CUENTA = PN_MES
        AND PERIODO_ANIO_CUENTA = PN_ANIO;
    IF LV_SALDO >= 0 THEN
        RETURN TRUE;
    ELSE
        RETURN FALSE;
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20001, 'FU_EXISTENCIA_CUENTA Ha ocurrido un error: '
            || SQLCODE
            || SQLERRM);
END FU_ES_SALDO_POSITIVO;
/