------------------------------------------------------ Función para calcular el saldo actual de una cuenta de cobro
CREATE OR REPLACE FUNCTION FU_CALC_V_ACTUAL (
    PK_CONJUNTO IN CONJUNTO.COD_CONJUNTO%TYPE,
    PK_BLOQUE IN APARTAMENTO.COD_BLOQUE%TYPE,
    PK_APTO IN APARTAMENTO.COD_APARTAMENTO%TYPE,
    PN_MES IN CUENTA_COBRO.PERIODO_MES_CUENTA%TYPE,
    PN_ANIO IN CUENTA_COBRO.PERIODO_ANIO_CUENTA%TYPE
) RETURN CUENTA_COBRO.SALDO_ACTUAL%TYPE AS
    LS_ACTUAL CUENTA_COBRO.SALDO_ACTUAL%TYPE;
BEGIN
    SELECT
        SALDO_ACTUAL INTO LS_ACTUAL
    FROM
        CUENTA_COBRO
    WHERE
        PERIODO_MES_CUENTA = PN_MES
        AND PERIODO_ANIO_CUENTA = PN_ANIO
        AND COD_CONJUNTO = PK_CONJUNTO
        AND COD_BLOQUE = PK_BLOQUE
        AND COD_APARTAMENTO = PK_APTO;
    RETURN LS_ACTUAL;
EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20001, 'FU_CALC_V_ACTUAL Ha ocurrido un error: '
            || SQLCODE
            || SQLERRM);
END FU_CALC_V_ACTUAL;
/

------------------------------------------------------ Función para calcular el saldo pendiente de una cuenta de cobro
CREATE OR REPLACE FUNCTION FU_CALC_V_PENDIENTE (
    PK_CONJUNTO IN CONJUNTO.COD_CONJUNTO%TYPE,
    PK_BLOQUE IN APARTAMENTO.COD_BLOQUE%TYPE,
    PK_APTO IN APARTAMENTO.COD_APARTAMENTO%TYPE,
    PN_MES IN CUENTA_COBRO.PERIODO_MES_CUENTA%TYPE,
    PN_ANIO IN CUENTA_COBRO.PERIODO_ANIO_CUENTA%TYPE
) RETURN CUENTA_COBRO.SALDO_PENDIENTE%TYPE AS
    LS_PENDIENTE CUENTA_COBRO.SALDO_PENDIENTE%TYPE;
BEGIN
    SELECT
        SALDO_PENDIENTE INTO LS_PENDIENTE
    FROM
        CUENTA_COBRO
    WHERE
        PERIODO_MES_CUENTA = PN_MES
        AND PERIODO_ANIO_CUENTA = PN_ANIO
        AND COD_CONJUNTO = PK_CONJUNTO
        AND COD_BLOQUE = PK_BLOQUE
        AND COD_APARTAMENTO = PK_APTO;
    RETURN LS_PENDIENTE;
EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20001, 'FU_CALC_V_PENDIENTE Ha ocurrido un error: '
            || SQLCODE
            || SQLERRM);
END FU_CALC_V_PENDIENTE;
/

------------------------------------------------------ Función para saber si existe una cuenta de cobro dada
CREATE OR REPLACE FUNCTION FU_EXISTENCIA_CUENTA (
    PK_CONJUNTO IN CONJUNTO.COD_CONJUNTO%TYPE,
    PK_BLOQUE IN APARTAMENTO.COD_BLOQUE%TYPE,
    PK_APTO IN APARTAMENTO.COD_APARTAMENTO%TYPE,
    PN_MES IN CUENTA_COBRO.PERIODO_MES_CUENTA%TYPE,
    PN_ANIO IN CUENTA_COBRO.PERIODO_ANIO_CUENTA%TYPE
) RETURN BOOLEAN AS
    LK_CUENTA CUENTA_COBRO.COD_CUENTA_COBRO%TYPE;
BEGIN
    SELECT
        COD_CUENTA_COBRO INTO LK_CUENTA
    FROM
        CUENTA_COBRO
    WHERE
        COD_CONJUNTO = PK_CONJUNTO
        AND COD_BLOQUE = PK_BLOQUE
        AND COD_APARTAMENTO = PK_APTO
        AND PERIODO_ANIO_CUENTA = PN_MES
        AND PERIODO_ANIO_CUENTA = PN_ANIO;
    IF LK_CUENTA IS NOT NULL THEN
        RETURN TRUE;
    ELSE
        RETURN FALSE;
    END IF;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN FALSE;
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20001, 'FU_EXISTENCIA_CUENTA Ha ocurrido un error: '
            || SQLCODE
            || SQLERRM);
END FU_EXISTENCIA_CUENTA;
/

-- Función que devuelve un listado de las personas asociadas a su apartamento.

CREATE OR REPLACE FUNCTION FU_MOSTRAR_PERSONAS(
    PK_APTO IN APARTAMENTO.COD_APARTAMENTO%TYPE,
    PK_BLOQUE IN APARTAMENTO.COD_BLOQUE%TYPE,
    PK_CONJUNTO IN CONJUNTO.COD_CONJUNTO%TYPE
) RETURN SYS_REFCURSOR AS
    LR_PERSONA_APTO SYS_REFCURSOR;
BEGIN
    OPEN LR_PERSONA_APTO FOR
        SELECT
            DISTINCT A.COD_APARTAMENTO,
            A.COD_BLOQUE,
            C.NOMBRE_CONJUNTO,
            P.NOMBRE1_PERSONA,
            P.APELLIDO1_PERSONA
        FROM
            APARTAMENTO         A,
            CONJUNTO            C,
            PERSONA             P,
            RESIDE              R,
            PERSONA_RESPONSABLE PR,
            PERSONA_RESIDENTE   PV
        WHERE
            C.COD_CONJUNTO = A.COD_CONJUNTO
            AND A.COD_APARTAMENTO = R.COD_APARTAMENTO
            AND A.COD_BLOQUE = R.COD_BLOQUE
            AND A.COD_CONJUNTO = R.COD_CONJUNTO
            AND PV.COD_PERSONA = R.COD_PERSONA
            AND A.COD_PERSONA = PR.COD_PERSONA;
    RETURN LR_PERSONA_APTO;
EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20001, 'FU_MOSTRAR_PERSONAS Ha ocurrido un error: '
            || SQLCODE
            || SQLERRM);
END FU_MOSTRAR_PERSONAS;
/

-- Función que devuelve la cuenta de cobro de un apartamento para un mes dado.
CREATE OR REPLACE FUNCTION FU_MOSTRAR_CUENTA(
    PN_CONJUNTO IN CONJUNTO.NOMBRE_CONJUNTO%TYPE,
    PK_APTO IN APARTAMENTO.COD_APARTAMENTO%TYPE,
    PK_BLOQUE IN APARTAMENTO.COD_BLOQUE%TYPE,
    PID_PERSONA IN PERSONA.IDENTIFICACION_PERSONA%TYPE,
    PN_MES IN CUENTA_COBRO.PERIODO_MES_CUENTA%TYPE,
    PN_ANIO IN CUENTA_COBRO.PERIODO_ANIO_CUENTA%TYPE
) RETURN SYS_REFCURSOR AS
    LR_CUENTA_APTO SYS_REFCURSOR;
BEGIN
    OPEN LR_CUENTA_APTO FOR
        SELECT
            NOMBRE_CONJUNTO,
            A.COD_APARTAMENTO,
            A.COD_BLOQUE,
            AREA_APARTAMENTO,
            COEF_ADMINISTRACION,
            NOMBRE1_PERSONA,
            APELLIDO1_PERSONA,
            PERIODO_MES_CUENTA ||'/'|| PERIODO_ANIO_CUENTA,
            SALDO_PENDIENTE,
            VALOR_MORA,
            VALOR_DESCUENTO,
            SALDO_ACTUAL
        FROM
            CONJUNTO            C,
            APARTAMENTO         A,
            PERSONA_RESPONSABLE PR,
            PERSONA             P,
            CUENTA_COBRO        CC
        WHERE
            NOMBRE_CONJUNTO = PN_CONJUNTO
            AND C.COD_CONJUNTO = A.COD_CONJUNTO
            AND A.COD_CONJUNTO = CC.COD_CONJUNTO
            AND A.COD_BLOQUE = CC.COD_BLOQUE
            AND A.COD_APARTAMENTO = CC.COD_APARTAMENTO
            AND P.IDENTIFICACION_PERSONA = PID_PERSONA
            AND A.COD_PERSONA = PR.COD_PERSONA
            AND PR.COD_PERSONA = P.COD_PERSONA
            AND PERIODO_MES_CUENTA = PN_MES
            AND PERIODO_ANIO_CUENTA = PN_ANIO;
    RETURN LR_CUENTA_APTO;
EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20001, 'FU_MOSTRAR_CUENTA Ha ocurrido un error: '
            || SQLCODE
            || SQLERRM);
END FU_MOSTRAR_CUENTA;
/